#include "cursor_image.h"

char *cursor_arrow_data =
"                  "
" x                "
" xx               "
" xxx              "
" xxxx             "
" xxxxx            "
" xxxxxx           "
" xxxxxxx          "
" xxxxxxxx         "
" xxxxx            "
" xx xx            "
" x   xx           "
"     xx           "
"      xx          "
"      xx          "
"                  "
"                  "
"                  ";

char *cursor_arrow_mask =
"xx                "
"xxx               "
"xxxx              "
"xxxxx             "
"xxxxxx            "
"xxxxxxx           "
"xxxxxxxx          "
"xxxxxxxxx         "
"xxxxxxxxxx        "
"xxxxxxxxxx        "
"xxxxxxx           "
"xxx xxxx          "
"xx  xxxx          "
"     xxxx         "
"     xxxx         "
"      xx          "
"                  "
"                  ";

char* cursor_xterm_data = 
"                "
"     xxx xxx    "
"       xxx      "
"        x       "
"        x       "
"        x       "
"        x       "
"        x       "
"        x       "
"        x       "
"        x       "
"        x       "
"        x       "
"       xxx      "
"     xxx xxx    "
"                ";

char *cursor_xterm_mask = 
"    xxxx xxxx   "
"    xxxxxxxxx   "
"    xxxxxxxxx   "
"      xxxxx     "
"       xxx      "
"       xxx      "
"       xxx      "
"       xxx      "
"       xxx      "
"       xxx      "
"       xxx      "
"       xxx      "
"      xxxxx     "
"    xxxxxxxxx   "
"    xxxxxxxxx   "
"    xxxx xxxx   ";

char *cursor_fleur_data = 
"                "
"       xx       "
"      xxxx      "
"     xxxxxx     "
"       xx       "
"   x   xx   x   "
"  xx   xx   xx  "
" xxxxxxxxxxxxxx "
" xxxxxxxxxxxxxx "
"  xx   xx   xx  "
"   x   xx   x   "
"       xx       "
"     xxxxxx     "
"      xxxx      "
"       xx       "
"                ";

char *cursor_fleur_mask = 
"      xxxx      "
"      xxxxx     "
"     xxxxxx     "
"    xxxxxxxx    "
"   x xxxxxx x   "
"  xxx xxxx xxx  "
"xxxxxxxxxxxxxxxx"
"xxxxxxxxxxxxxxxx"
"xxxxxxxxxxxxxxxx"
"xxxxxxxxxxxxxxxx"
"  xxx xxxx xxx  "
"   x xxxxxx x   "
"    xxxxxxxx    "
"     xxxxxx     "
"      xxxx      "
"      xxxx      ";

char *cursor_plus_data = 
"            "
"     xx     "
"     xx     "
"     xx     "
"     xx     "
" xxxxxxxxxx "
" xxxxxxxxxx "
"     xx     "
"     xx     "
"     xx     "
"     xx     "
"            ";

char *cursor_plus_mask = 
"    xxxx    "
"    xxxx    "
"    xxxx    "
"    xxxx    "
"xxxxxxxxxxxx"
"xxxxxxxxxxxx"
"xxxxxxxxxxxx"
"xxxxxxxxxxxx"
"    xxxx    "
"    xxxx    "
"    xxxx    "
"    xxxx    ";

char *cursor_hand_data =
"                  "
"        xx        "
"       x  x       "
"      x    x      "
"     x      x     "
"     x      x     "
"    x        x    "
"     x      x     "
"     x      x     "
"      x    x      "
"       x  x       "
"        xx        "
"         x        "
"         x        "
"                  ";

char *cursor_hand_mask =
"                  "
"        xxxx      "
"       xxxxx      "
"      xxxxxxx     "
"     xxxxxxxxx    "
"     xxxxxxxxx    "
"    xxxxxxxxxx    "
"     xxxxxxxxx    "
"     xxxxxxxxx    "
"      xxxxxxx     "
"       xxxxx      "
"        xxxx      "
"         xx       "
"         xx       "
"                  ";

char *cursor_left_up_resize_data =
"xxxxxxxxxxxxx     "
"xxxxxxxxxxxxx     "
"xxxxxxx           "
"xxxx xxxx         "
"xxxx  xxxx        "
"xxxx   xxxx       "
"xxxx    xxxx      "
"xxxx     xxxx     "
"xxxx      xxxx    "
"           xxxx   "
"            xxxx  "
"             xxxx ";

char *cursor_left_up_resize_mask =
"xxxxxxxxxxxxxx    "
"xxxxxxxxxxxxxx    "
"xxxxxxxxxxxxxx    "
"xxxxxxxxx         "
"xxxxx xxxxx       "
"xxxxx  xxxxx      "
"xxxxx   xxxxx     "
"xxxxx    xxxxx    "
"xxxxx     xxxxx   "
"           xxxxx  "
"            xxxxx "
"             xxxxx";